import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Platform (Packet 01)
// ---------------------------------------------------------------------------

// Better Auth's tables, generated by `bunx @better-auth/cli generate`. Its
// `organizations` table IS the tenant boundary from Build Plan §6.1 — the
// organization plugin is pointed at that name, so there is exactly one
// organization table and `session.activeOrganizationId` is the id every
// business table below scopes by.
export * from "./auth-schema";

// Cache of the last successfully verified license (for offline boots).
export const licenseCache = pgTable("license_cache", {
  id: integer("id").primaryKey().default(1), // singleton row
  tier: text("tier").notNull().default("free"),
  modules: jsonb("modules").$type<string[]>().notNull().default([]),
  token: text("token"),
  refreshedAt: timestamp("refreshed_at").defaultNow().notNull(),
});

// ---------------------------------------------------------------------------
// CRM
// ---------------------------------------------------------------------------

export const companies = pgTable(
  "companies",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    name: text("name").notNull(),
    website: text("website"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("companies_org_idx").on(t.organizationId)],
);

export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    companyId: uuid("company_id"),
    kind: text("kind").notNull().default("customer"), // customer|lead|supplier
    name: text("name").notNull(),
    email: text("email"),
    phone: text("phone"),
    // for customer-portal row scoping: links a portal user to their contact record
    portalUserId: text("portal_user_id"),
    /**
     * Bearer of this customer's portal link.
     *
     * A token rather than an account: the people being invoiced are customers
     * of a small business, and asking them to create a login to look at a bill
     * is how a bill goes unread. Null until someone asks for the link;
     * reissuing revokes the old one.
     */
    portalToken: text("portal_token"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("contacts_org_idx").on(t.organizationId),
    index("contacts_portal_user_idx").on(t.portalUserId),
  ],
);

export const deals = pgTable(
  "deals", // Pro-gated in UI, table lives in core
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    title: text("title").notNull(),
    stage: text("stage").notNull().default("lead"), // lead|qualified|proposal|won|lost
    valueCents: integer("value_cents").notNull().default(0),
    ownerId: text("owner_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("deals_org_idx").on(t.organizationId)],
);

export const activities = pgTable(
  "activities",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    dealId: uuid("deal_id"),
    type: text("type").notNull(), // call|email|note|meeting
    body: text("body"),
    occurredAt: timestamp("occurred_at").defaultNow().notNull(),
  },
  (t) => [index("activities_org_idx").on(t.organizationId)],
);

export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    title: text("title").notNull(),
    dueAt: timestamp("due_at"),
    assigneeId: text("assignee_id"),
    done: boolean("done").notNull().default(false),
  },
  (t) => [index("tasks_org_idx").on(t.organizationId)],
);

export const tags = pgTable(
  "tags",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    name: text("name").notNull(),
  },
  (t) => [index("tags_org_idx").on(t.organizationId)],
);

export const taggables = pgTable(
  "taggables",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tagId: uuid("tag_id").notNull(),
    entityType: text("entity_type").notNull(), // "contact" | "deal"
    entityId: uuid("entity_id").notNull(),
  },
  (t) => [index("taggables_entity_idx").on(t.entityType, t.entityId)],
);

// ---------------------------------------------------------------------------
// Invoicing — money is integer cents, tax is basis points
// ---------------------------------------------------------------------------

export const quotes = pgTable(
  "quotes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    number: text("number").notNull(),
    status: text("status").notNull().default("draft"), // draft|sent|accepted|declined
    currency: text("currency").notNull().default("USD"),
    subtotalCents: integer("subtotal_cents").notNull().default(0),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("quotes_org_idx").on(t.organizationId)],
);

export const quoteLines = pgTable(
  "quote_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    quoteId: uuid("quote_id").notNull(),
    description: text("description").notNull(),
    quantity: integer("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
    taxRateBp: integer("tax_rate_bp").notNull().default(0),
  },
  (t) => [index("quote_lines_quote_idx").on(t.quoteId)],
);

export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    quoteId: uuid("quote_id"), // set when converted from a quote
    number: text("number").notNull(),
    status: text("status").notNull().default("draft"), // draft|open|partial|paid|void
    currency: text("currency").notNull().default("USD"),
    issueDate: timestamp("issue_date").defaultNow().notNull(),
    dueDate: timestamp("due_date"),
    subtotalCents: integer("subtotal_cents").notNull().default(0),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull().default(0),
    lastReminderAt: timestamp("last_reminder_at"),
  },
  (t) => [
    index("invoices_org_idx").on(t.organizationId),
    index("invoices_contact_idx").on(t.contactId),
  ],
);

export const invoiceLines = pgTable(
  "invoice_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    invoiceId: uuid("invoice_id").notNull(),
    description: text("description").notNull(),
    quantity: integer("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
    taxRateBp: integer("tax_rate_bp").notNull().default(0),
  },
  (t) => [index("invoice_lines_invoice_idx").on(t.invoiceId)],
);

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    invoiceId: uuid("invoice_id").notNull(),
    amountCents: integer("amount_cents").notNull(), // supports partial payments
    method: text("method").notNull().default("manual"), // manual|stripe|paypal
    gatewayRef: text("gateway_ref"),
    receivedAt: timestamp("received_at").defaultNow().notNull(),
  },
  (t) => [
    index("payments_org_idx").on(t.organizationId),
    index("payments_invoice_idx").on(t.invoiceId),
  ],
);

export const recurringProfiles = pgTable(
  "recurring_profiles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id").notNull(),
    interval: text("interval").notNull(), // monthly|yearly
    nextRunAt: timestamp("next_run_at").notNull(),
    templateJson: jsonb("template_json")
      .$type<{ lines: unknown[] }>()
      .notNull(),
    active: boolean("active").notNull().default(true),
  },
  (t) => [index("recurring_profiles_org_idx").on(t.organizationId)],
);

export const creditNotes = pgTable(
  "credit_notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    invoiceId: uuid("invoice_id"),
    amountCents: integer("amount_cents").notNull(),
    reason: text("reason"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("credit_notes_org_idx").on(t.organizationId)],
);

// Per-org sequential document numbering (INV-0001). One row per org per kind;
// bumped inside the invoice transaction with SELECT ... FOR UPDATE.
export const documentCounters = pgTable(
  "document_counters",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    kind: text("kind").notNull(), // invoice|quote
    lastNumber: integer("last_number").notNull().default(0),
  },
  (t) => [index("document_counters_org_kind_idx").on(t.organizationId, t.kind)],
);

// ---------------------------------------------------------------------------
// Bookkeeping (double-entry)
// ---------------------------------------------------------------------------

export const accounts = pgTable(
  "accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    code: text("code").notNull(),
    name: text("name").notNull(),
    type: text("type").notNull(), // asset|liability|equity|income|expense
  },
  (t) => [index("accounts_org_idx").on(t.organizationId)],
);

export const journalEntries = pgTable(
  "journal_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    memo: text("memo"),
    source: text("source"), // "invoice:<id>" | "payment:<id>" | "manual"
    postedAt: timestamp("posted_at").defaultNow().notNull(),
  },
  (t) => [index("journal_entries_org_idx").on(t.organizationId)],
);

export const journalLines = pgTable(
  "journal_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    entryId: uuid("entry_id").notNull(),
    accountId: uuid("account_id").notNull(),
    debitCents: integer("debit_cents").notNull().default(0),
    creditCents: integer("credit_cents").notNull().default(0),
  },
  (t) => [index("journal_lines_entry_idx").on(t.entryId)],
);

export const expenses = pgTable(
  "expenses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    accountId: uuid("account_id"),
    amountCents: integer("amount_cents").notNull(),
    vendor: text("vendor"),
    receiptFileKey: text("receipt_file_key"), // storage-adapter key (local by default)
    spentAt: timestamp("spent_at").defaultNow().notNull(),
  },
  (t) => [index("expenses_org_idx").on(t.organizationId)],
);

export const bankImports = pgTable(
  "bank_imports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    filename: text("filename").notNull(),
    importedAt: timestamp("imported_at").defaultNow().notNull(),
  },
  (t) => [index("bank_imports_org_idx").on(t.organizationId)],
);

export const bankTransactions = pgTable(
  "bank_transactions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    importId: uuid("import_id").notNull(),
    date: timestamp("date").notNull(),
    description: text("description"),
    amountCents: integer("amount_cents").notNull(),
    matchedEntryId: uuid("matched_entry_id"), // reconciliation link (Pro)
  },
  (t) => [index("bank_transactions_org_idx").on(t.organizationId)],
);

// ---------------------------------------------------------------------------
// Embeddable forms
//
// A form is pasted into any external site — the customer's marketing pages, a
// landing page, anywhere — and posts straight to the customer's own instance.
// Submissions never travel through Foothills infrastructure.
// ---------------------------------------------------------------------------

export const forms = pgTable(
  "forms",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    // public identifier, safe to paste into a page's HTML
    key: text("key").notNull().unique(),
    name: text("name").notNull(),
    kind: text("kind").notNull().default("contact"), // contact|quote
    // domains permitted to post; empty means same-origin only
    allowedOrigins: jsonb("allowed_origins")
      .$type<string[]>()
      .notNull()
      .default([]),
    fields: jsonb("fields")
      .$type<
        { name: string; label: string; type: string; required?: boolean }[]
      >()
      .notNull()
      .default([]),
    redirectUrl: text("redirect_url"),
    notifyEmail: text("notify_email"),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("forms_org_idx").on(t.organizationId)],
);

export const formSubmissions = pgTable(
  "form_submissions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    formId: uuid("form_id").notNull(),
    contactId: uuid("contact_id"),
    quoteId: uuid("quote_id"),
    payload: jsonb("payload").$type<Record<string, string>>().notNull(),
    origin: text("origin"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("form_submissions_org_idx").on(t.organizationId),
    index("form_submissions_form_idx").on(t.formId),
  ],
);
