import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

// ---------------------------------------------------------------------------
// Platform (Packet 01)
// ---------------------------------------------------------------------------

// Better Auth's tables, generated by `bunx @better-auth/cli generate`. Its
// `organizations` table IS the tenant boundary from Build Plan §6.1 — the
// organization plugin is pointed at that name, so there is exactly one
// organization table and `session.activeOrganizationId` is the id every
// business table below scopes by.
export * from "./auth-schema";

// Cache of the last successfully verified license (for offline boots).
export const licenseCache = pgTable("license_cache", {
  id: integer("id").primaryKey().default(1), // singleton row
  tier: text("tier").notNull().default("free"),
  modules: jsonb("modules").$type<string[]>().notNull().default([]),
  token: text("token"),
  refreshedAt: timestamp("refreshed_at").defaultNow().notNull(),
});

// ---------------------------------------------------------------------------
// CRM
// ---------------------------------------------------------------------------

export const companies = pgTable(
  "companies",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    name: text("name").notNull(),
    website: text("website"),
    sector: text("sector"),
    /** Headcount band, not an exact number — nobody knows the exact number. */
    size: integer("size"),
    phone: text("phone"),
    linkedinUrl: text("linkedin_url"),
    address: text("address"),
    city: text("city"),
    state: text("state"),
    postcode: text("postcode"),
    country: text("country"),
    revenue: text("revenue"),
    description: text("description"),
    /** Whose account this is. A platform user, not a separate sales record. */
    ownerId: text("owner_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("companies_org_idx").on(t.organizationId)],
);

export const contacts = pgTable(
  "contacts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    companyId: uuid("company_id"),
    kind: text("kind").notNull().default("customer"), // customer|lead|supplier
    /**
     * The display name, always written as first + last.
     *
     * Kept rather than replaced: invoices, quotes and the customer portal all
     * read it, and a CRM rework is no reason to go and change how an invoice
     * addresses somebody. The CRM writes all three together.
     */
    name: text("name").notNull(),
    firstName: text("first_name"),
    lastName: text("last_name"),
    title: text("title"),
    linkedinUrl: text("linkedin_url"),
    /** Whose contact this is — a platform user. */
    ownerId: text("owner_id"),
    /**
     * The first email and phone, kept as plain columns.
     *
     * Everything that already invoices or emails a contact reads these, and a
     * business almost always has one address that matters. The labelled lists
     * below are the rest of them.
     */
    email: text("email"),
    phone: text("phone"),
    /**
     * Every way to reach them: [{ label: "work", value: "..." }].
     *
     * A contact with two numbers and nowhere to put the second is the gap
     * people notice first. A list rather than more columns, because the number
     * of them is not knowable in advance.
     */
    emails: jsonb("emails").$type<{ label: string; value: string }[]>(),
    phones: jsonb("phones").$type<{ label: string; value: string }[]>(),
    // for customer-portal row scoping: links a portal user to their contact record
    portalUserId: text("portal_user_id"),
    /**
     * Bearer of this customer's portal link.
     *
     * A token rather than an account: the people being invoiced are customers
     * of a small business, and asking them to create a login to look at a bill
     * is how a bill goes unread. Null until someone asks for the link;
     * reissuing revokes the old one.
     */
    portalToken: text("portal_token"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("contacts_org_idx").on(t.organizationId),
    index("contacts_portal_user_idx").on(t.portalUserId),
  ],
);

export const deals = pgTable(
  "deals",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    name: text("name").notNull(),
    companyId: uuid("company_id"),
    /**
     * Everyone involved, not one person.
     *
     * A deal at a company of any size has several people attached to it, and
     * the previous single `contactId` meant recording one and losing the rest.
     */
    contactIds: jsonb("contact_ids").$type<string[]>().default([]),
    category: text("category"),
    stage: text("stage").notNull().default("opportunity"),
    description: text("description"),
    amountCents: integer("amount_cents").notNull().default(0),
    expectedCloseOn: date("expected_close_on"),
    /**
     * Where the card sits in its column.
     *
     * A kanban that reorders itself on every load is not a kanban — people
     * arrange the column to mean something, and that arrangement has to
     * survive a refresh.
     */
    position: integer("position").notNull().default(0),
    /** Filed away rather than deleted: won and lost deals are the history. */
    archivedAt: timestamp("archived_at"),
    ownerId: text("owner_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (t) => [
    index("deals_org_idx").on(t.organizationId),
    index("deals_stage_idx").on(t.organizationId, t.stage),
  ],
);

/**
 * Notes against a contact or a deal, with files.
 *
 * One table rather than Atomic's two, matching how `taggables` already works
 * here — the shape is identical and two tables would mean two of every query.
 */
export const notes = pgTable(
  "notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    entityType: text("entity_type").notNull(), // "contact" | "deal"
    entityId: uuid("entity_id").notNull(),
    text: text("text").notNull(),
    /**
     * Files kept on disk under the data directory, recorded here.
     *
     * The path, not the bytes: a quote or a signed job sheet in a database
     * column bloats every backup and every query that touches the row.
     */
    attachments: jsonb("attachments")
      .$type<{ name: string; path: string; size: number; type: string }[]>()
      .default([]),
    authorId: text("author_id"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("notes_org_idx").on(t.organizationId),
    index("notes_entity_idx").on(t.entityType, t.entityId),
  ],
);

export const activities = pgTable(
  "activities",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    dealId: uuid("deal_id"),
    type: text("type").notNull(), // call|email|note|meeting
    body: text("body"),
    occurredAt: timestamp("occurred_at").defaultNow().notNull(),
  },
  (t) => [index("activities_org_idx").on(t.organizationId)],
);

export const tasks = pgTable(
  "tasks",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    title: text("title").notNull(),
    /** What kind of follow-up: call, email, meeting, other. */
    type: text("type"),
    /**
     * Who it is about. A task with no contact is a to-do list item; a task
     * with one is the follow-up that stops a deal going quiet, which is the
     * whole reason a CRM has tasks at all.
     */
    contactId: uuid("contact_id"),
    dealId: uuid("deal_id"),
    dueAt: timestamp("due_at"),
    assigneeId: text("assignee_id"),
    done: boolean("done").notNull().default(false),
  },
  (t) => [index("tasks_org_idx").on(t.organizationId)],
);

export const tags = pgTable(
  "tags",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    name: text("name").notNull(),
    /** Tags are scanned, not read. Without colour they are just more text. */
    color: text("color").notNull().default("#94a3b8"),
  },
  (t) => [index("tags_org_idx").on(t.organizationId)],
);

export const taggables = pgTable(
  "taggables",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    tagId: uuid("tag_id").notNull(),
    entityType: text("entity_type").notNull(), // "contact" | "deal"
    entityId: uuid("entity_id").notNull(),
  },
  (t) => [index("taggables_entity_idx").on(t.entityType, t.entityId)],
);

// ---------------------------------------------------------------------------
// Invoicing — money is integer cents, tax is basis points
// ---------------------------------------------------------------------------

export const quotes = pgTable(
  "quotes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    number: text("number").notNull(),
    status: text("status").notNull().default("draft"), // draft|sent|accepted|declined
    currency: text("currency").notNull().default("USD"),
    subtotalCents: integer("subtotal_cents").notNull().default(0),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull().default(0),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("quotes_org_idx").on(t.organizationId)],
);

export const quoteLines = pgTable(
  "quote_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    quoteId: uuid("quote_id").notNull(),
    description: text("description").notNull(),
    quantity: integer("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
    taxRateBp: integer("tax_rate_bp").notNull().default(0),
  },
  (t) => [index("quote_lines_quote_idx").on(t.quoteId)],
);

export const invoices = pgTable(
  "invoices",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id"),
    quoteId: uuid("quote_id"), // set when converted from a quote
    number: text("number").notNull(),
    status: text("status").notNull().default("draft"), // draft|open|partial|paid|void
    currency: text("currency").notNull().default("USD"),
    issueDate: timestamp("issue_date").defaultNow().notNull(),
    dueDate: timestamp("due_date"),
    subtotalCents: integer("subtotal_cents").notNull().default(0),
    taxCents: integer("tax_cents").notNull().default(0),
    totalCents: integer("total_cents").notNull().default(0),
    lastReminderAt: timestamp("last_reminder_at"),
  },
  (t) => [
    index("invoices_org_idx").on(t.organizationId),
    index("invoices_contact_idx").on(t.contactId),
  ],
);

export const invoiceLines = pgTable(
  "invoice_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    invoiceId: uuid("invoice_id").notNull(),
    description: text("description").notNull(),
    quantity: integer("quantity").notNull().default(1),
    unitPriceCents: integer("unit_price_cents").notNull(),
    taxRateBp: integer("tax_rate_bp").notNull().default(0),
  },
  (t) => [index("invoice_lines_invoice_idx").on(t.invoiceId)],
);

export const payments = pgTable(
  "payments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    invoiceId: uuid("invoice_id").notNull(),
    amountCents: integer("amount_cents").notNull(), // supports partial payments
    method: text("method").notNull().default("manual"), // manual|stripe|paypal
    gatewayRef: text("gateway_ref"),
    receivedAt: timestamp("received_at").defaultNow().notNull(),
  },
  (t) => [
    index("payments_org_idx").on(t.organizationId),
    index("payments_invoice_idx").on(t.invoiceId),
  ],
);

export const recurringProfiles = pgTable(
  "recurring_profiles",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    contactId: uuid("contact_id").notNull(),
    interval: text("interval").notNull(), // monthly|yearly
    nextRunAt: timestamp("next_run_at").notNull(),
    templateJson: jsonb("template_json")
      .$type<{ lines: unknown[] }>()
      .notNull(),
    active: boolean("active").notNull().default(true),
  },
  (t) => [index("recurring_profiles_org_idx").on(t.organizationId)],
);

export const creditNotes = pgTable(
  "credit_notes",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    invoiceId: uuid("invoice_id"),
    amountCents: integer("amount_cents").notNull(),
    reason: text("reason"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("credit_notes_org_idx").on(t.organizationId)],
);

// Per-org sequential document numbering (INV-0001). One row per org per kind;
// bumped inside the invoice transaction with SELECT ... FOR UPDATE.
export const documentCounters = pgTable(
  "document_counters",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    kind: text("kind").notNull(), // invoice|quote
    lastNumber: integer("last_number").notNull().default(0),
  },
  (t) => [index("document_counters_org_kind_idx").on(t.organizationId, t.kind)],
);

// ---------------------------------------------------------------------------
// Bookkeeping (double-entry)
// ---------------------------------------------------------------------------

export const accounts = pgTable(
  "accounts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    code: text("code").notNull(),
    name: text("name").notNull(),
    type: text("type").notNull(), // asset|liability|equity|income|expense
  },
  (t) => [index("accounts_org_idx").on(t.organizationId)],
);

export const journalEntries = pgTable(
  "journal_entries",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    memo: text("memo"),
    source: text("source"), // "invoice:<id>" | "payment:<id>" | "manual"
    postedAt: timestamp("posted_at").defaultNow().notNull(),
  },
  (t) => [index("journal_entries_org_idx").on(t.organizationId)],
);

export const journalLines = pgTable(
  "journal_lines",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    entryId: uuid("entry_id").notNull(),
    accountId: uuid("account_id").notNull(),
    debitCents: integer("debit_cents").notNull().default(0),
    creditCents: integer("credit_cents").notNull().default(0),
  },
  (t) => [index("journal_lines_entry_idx").on(t.entryId)],
);

export const expenses = pgTable(
  "expenses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    accountId: uuid("account_id"),
    amountCents: integer("amount_cents").notNull(),
    vendor: text("vendor"),
    receiptFileKey: text("receipt_file_key"), // storage-adapter key (local by default)
    spentAt: timestamp("spent_at").defaultNow().notNull(),
  },
  (t) => [index("expenses_org_idx").on(t.organizationId)],
);

export const bankImports = pgTable(
  "bank_imports",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    filename: text("filename").notNull(),
    importedAt: timestamp("imported_at").defaultNow().notNull(),
  },
  (t) => [index("bank_imports_org_idx").on(t.organizationId)],
);

export const bankTransactions = pgTable(
  "bank_transactions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    importId: uuid("import_id").notNull(),
    date: timestamp("date").notNull(),
    description: text("description"),
    amountCents: integer("amount_cents").notNull(),
    matchedEntryId: uuid("matched_entry_id"), // reconciliation link (Pro)
  },
  (t) => [index("bank_transactions_org_idx").on(t.organizationId)],
);

// ---------------------------------------------------------------------------
// Embeddable forms
//
// A form is pasted into any external site — the customer's marketing pages, a
// landing page, anywhere — and posts straight to the customer's own instance.
// Submissions never travel through Foothills infrastructure.
// ---------------------------------------------------------------------------

export const forms = pgTable(
  "forms",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    // public identifier, safe to paste into a page's HTML
    key: text("key").notNull().unique(),
    name: text("name").notNull(),
    kind: text("kind").notNull().default("contact"), // contact|quote
    /**
     * Which form a submission came from, in one word.
     *
     * A business with a contact form on every page cannot tell them apart from
     * the fields alone — every one collects a name and an email. The tag is
     * what makes "where did this come from" answerable.
     */
    tag: text("tag"),
    /**
     * Optional look. Kept small on purpose: a colour and a corner radius cover
     * matching a site, and anything more is a stylesheet somebody should own
     * themselves rather than configure in a form builder.
     */
    style: jsonb("style").$type<{
      accent?: string;
      radius?: string;
      font?: string;
    }>(),
    // domains permitted to post; empty means same-origin only
    allowedOrigins: jsonb("allowed_origins")
      .$type<string[]>()
      .notNull()
      .default([]),
    fields: jsonb("fields")
      .$type<
        { name: string; label: string; type: string; required?: boolean }[]
      >()
      .notNull()
      .default([]),
    redirectUrl: text("redirect_url"),
    notifyEmail: text("notify_email"),
    active: boolean("active").notNull().default(true),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [index("forms_org_idx").on(t.organizationId)],
);

export const formSubmissions = pgTable(
  "form_submissions",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    organizationId: text("organization_id").notNull(),
    formId: uuid("form_id").notNull(),
    contactId: uuid("contact_id"),
    quoteId: uuid("quote_id"),
    payload: jsonb("payload").$type<Record<string, string>>().notNull(),
    origin: text("origin"),
    userAgent: text("user_agent"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => [
    index("form_submissions_org_idx").on(t.organizationId),
    index("form_submissions_form_idx").on(t.formId),
  ],
);

/**
 * Roles a business defined for itself.
 *
 * Better Auth's dynamic access control reads this when checking a permission
 * and merges what it finds with the roles compiled in. Written by its own
 * endpoints, never by us — the shape, including permissions being JSON in a
 * text column, is its contract rather than a choice.
 */
export const organizationRole = pgTable(
  "organization_role",
  {
    id: text("id").primaryKey(),
    organizationId: text("organization_id").notNull(),
    role: text("role").notNull(),
    permission: text("permission").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at"),
  },
  (t) => [
    index("organization_role_org_idx").on(t.organizationId),
    index("organization_role_name_idx").on(t.role),
  ],
);
